# Generated by Django 5.0.1 on 2024-01-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IA', '0002_card_image_alter_card_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
