# Generated by Django 5.0.1 on 2024-01-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IA', '0003_alter_card_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='serial',
            field=models.CharField(default='WE-000.001', max_length=20),
        ),
    ]
