# Generated by Django 5.0.1 on 2024-01-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IA', '0004_card_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='user',
            field=models.IntegerField(default=1),
        ),
    ]
