# Generated by Django 5.0.1 on 2024-01-29 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IA', '0007_alter_card_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='IA.card'),
        ),
    ]
