# Generated by Django 5.0.1 on 2024-01-31 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IA', '0011_alter_status_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.BinaryField(),
        ),
    ]
