# Generated by Django 5.0.1 on 2024-01-31 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IA', '0012_alter_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='category',
            field=models.CharField(choices=[('Weapons', 'Option1'), ('Potions', 'Option2'), ('Armors', 'Option3')], default='Weapons', max_length=20),
        ),
    ]
